-- armoredturretflash

return {
  ["armoredturretflash"] = {
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 22,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        alwaysvisible      = true,
        colormap           = [[0.9 0.9 0.7 0.01	0.5 0.4 0.3 0.02	0.9 0.1 0.1 0.02		0 0 0 0.0]],
        directional        = true,
        emitrot            = 2,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 2,
        particlelifespread = 1,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = [[-6 i3]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.5,
        sizemod            = 1.0,
        texture            = [[firesprite]],
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 8,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.4 0.4 0.4 0.5   0.4 0.4 0.4 0.3	0.0 0.0 0.0 0.0]],
        directional        = true,
        emitrot            = 2,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[r-0.1 r0.1, r-0.1 r1, r-0.1 r0.1]],
        numparticles       = 1,
        particlelife       = 20,
        particlelifespread = 15,
        particlesize       = 5,
        particlesizespread = 4,
        particlespeed      = [[-10 i7]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
    whiteglow = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 3.5,
        maxheat            = 15,
        pos                = [[0, 0, 0]],
        size               = 9,
        sizegrowth         = 40,
        speed              = [[0, 0, 0]],
        texture            = [[glow]],
      },
    },
  },

}

