-- missile_explosion

return {
  ["bgantimatter"] = {
   
  groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.3,
      circlegrowth       = 2,
      flashalpha         = 0.3,
      flashsize          = 25,
      ground             = true,
      ttl                = 10,
      water              = true,
      color = {
        [1]  = 0,
        [2]  = 0.5,
        [3]  = 1,
      },
    },
	
	spark = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
      colormap           = [[1.0 1.0 1.0 0.04	0.2 0.5 0.9 0.01	0.1 0.5 0.7 0.01]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.005, 0]],
        numparticles       = 2,
        particlelife       = 5,
        particlelifespread = 8,
        particlesize       =0.5,
        particlesizespread =0.05,
        particlespeed      = 8,
        particlespeedspread = 3,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.8,
        sizemod            = 0.9999,
        texture            = [[randdots]],
        useairlos          = false,
      },
    },
	
    poof01 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.04	0.2 0.5 0.9 0.01	0.1 0.5 0.7 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[dir]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 5,
        particlesize       =0.05,
        particlesizespread = 0.15,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[antimatterone]],
        useairlos          = false,
      },
    },
  poof02 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
       colormap           = [[1.0 1.0 1.0 0.04	0.2 0.5 0.9 0.01	0.1 0.5 0.7 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[dir]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 5,
        particlesize       =0.05,
        particlesizespread =0.05,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[antimatertwo]],
        useairlos          = false,
      },
    },
	
  },

}

