-- dirt

return {
  ["centerfire"] = {
    dirtgw = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
             colormap           = [[0.25 0.20 0.10 0.1	1 0.8 0 0.5]],
        directional        = true,
        emitrot            = 2,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 40,
        particlelifespread = 2,
        particlesize       = [[3]],
        particlesizespread = 9,
        particlespeed      = 6,
        particlespeedspread =2,
        pos                = [[0, 1 , 0]],
        sizegrowth         = 0.99,
        sizemod            = 0.9,
        texture            = [[fire3]],
        useairlos          = false,
      },
    },
	
	dirtgwx = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
             colormap           = [[0.25 0.20 0.10 0.1	0.8 0.5 0 0.3]],
        directional        = true,
        emitrot            = 2,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 40,
        particlelifespread = 2,
        particlesize       = [[3]],
        particlesizespread = 9,
        particlespeed      = 6,
        particlespeedspread =2,
        pos                = [[0, 1 , 0]],
        sizegrowth         = 0.99,
        sizemod            = 0.9,
        texture            = [[fire2]],
        useairlos          = false,
      },
    },
	
    firballz = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
             colormap           = [[0.25 0.20 0.10 0.1	0.9 0.6 0 0.4]],
        directional        = true,
        emitrot            = 5,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 35,
        particlelifespread = 9,
        particlesize       = [[3]],
        particlesizespread = 32,
        particlespeed      = 7,
        particlespeedspread = 1,
        pos                = [[0, 25 , 0]],
        sizegrowth         = 0.99,
        sizemod            = 0.9,
        texture            = [[fire6]],
        useairlos          = false,
      },
    },
	
	  highflamez = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
             colormap           = [[0.25 0.20 0.10 0.1	1 0.8 0.4 0.5]],
        directional        = true,
        emitrot            = 5,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 1,
        particlelifespread = 50,
        particlesize       = [[53]],
        particlesizespread = 22,
        particlespeed      = 6,
        particlespeedspread = 3,
        pos                = [[0, 1 , 0]],
        sizegrowth         = 0.99,
        sizemod            = 0.9,
        texture            = [[fire4]],
        useairlos          = false,
      },
    },
	
	
  },

}