-- dirt

return {
  ["chedgehogfired"] = {
        
	groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.5,
      circlegrowth       = 8,
      flashalpha         = 0.9,
      flashsize          = 120,
      ground             = true,
      ttl                = 17,
      water              = true,
      color = {
        [1]  = 0,
        [2]  = 0.30000001192093,
        [3]  = 1,
      },
    },
    poof01 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      properties = {
        airdrag            = 0.8,
         colormap           = [[1 0.5 0.25 .01   1 0.3 0.05 .01		0 0 0 0.01]],
        directional        = false,
        emitrot            = 15,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 32,
        particlelife       = 3,
        particlelifespread = 350,
        particlesize       = 55,
        particlesizespread = 3,
        particlespeed      = 32,
        particlespeedspread = 3,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[4explo]],
        useairlos          = false,
      },
    },
    poof02 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
		colormap           = [[1 0.5 0.25 .01   1 0.3 0.05 .01		0 0 0 0.01]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.5, 0]],
        numparticles       = 64,
        particlelife       = 3,
        particlelifespread = 350,
        particlesize       = 50,
        particlesizespread = 1,
        particlespeed      = 52,
        particlespeedspread = 32,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[randdots]],
        useairlos          = false,
      },
    },
    poof03 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      properties = {
        airdrag            = 0.8,
	colormap           = [[1 0.5 0.25 .01   1 0.3 0.05 .01		0 0 0 0.01]],
        directional        = false,
        emitrot            = 15,
        emitrotspread      = 90,
        emitvector         = [[0, -1, 0]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 32,
        particlelife       = 3,
        particlelifespread = 350,
        particlesize       = 55,
        particlesizespread = 3,
        particlespeed      = 32,
        particlespeedspread = 3,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[4explo]],
        useairlos          = false,
      },
    },
    pop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.4,
        maxheat            = 10,
        pos                = [[r-10 r10, 0, r-10 r10]],
        size               = 1,
        sizegrowth         = 37,
        speed              = [[0, 0, 0]],
        texture            = [[nuke]],
      },
    },    
	
	popl1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.4,
        maxheat            = 10,
        pos                = [[r-10 r10, 0, r-10 r10]],
        size               = 1,
        sizegrowth         = 37,
        speed              = [[0, 0, 0]],
        texture            = [[novabg]],
      },
    },
    pop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.6,
        maxheat            = 15,
        pos                = [[r-150 r150, 0, r-300 r150]],
        size               = 1,
        sizegrowth         = 30,
        speed              = [[0, 0, 0]],
        texture            = [[redexplo]],
      },
    },
  

  
  sparkredX2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.5 0.25 .01   1 0.3 0.05 .01		0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[dir]],
        gravity            = [[0, -0.07, 0]],
        numparticles       = 3,
        particlelife       = 19,
        particlelifespread = 11,
        particlesize       = 0.5,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[0.0 r.35]],
        sizemod            = 1.2,
        texture            = [[gunshot]],
        useairlos          = false,
      },
    },
  
  
  },

}