-- dirt

return {
  ["darkCloud"] = {
poof01 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[0.1 0.2 0.6 1.0	0.1 0.1 0.3 1.0		0 0 0 0.0]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 12,
        emitvector         = [[0, 0, 1]],
        gravity            = [[0, 0, 0]],
        numparticles       = 8,
        particlelife       = 42,
        particlelifespread = 5,
        particlesize       = 5,
        particlesizespread = 2,
        particlespeed      = 3,
        particlespeedspread = 5,
        pos                = [[r-1 r1, 1, r-1 r1]],
        sizegrowth         = 1.0001,
        sizemod            = 1.0,
        texture            = [[citadellcloud]],
        useairlos          = true,
      },
    },
    
	 sparkcloudg = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = false,
      properties = {
        airdrag            = 0.4,
        alwaysvisible      = true,
         colormap           = [[0.1 0.2 0.6 1.0	0.1 0.1 0.3 0.9		0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 3,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.0 0.0, 0]],
        numparticles       = 5,
        particlelife       = 12,
        particlelifespread = 5,
        particlesize       = [[22 r4]],
        particlesizespread = 10,
        particlespeed      = 5,
        particlespeedspread = 6,
        pos                = [[r-0.5 r0.5, 1 r2, r-0.5 r0.5]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[citadellcloud]],
        useairlos          = true,
      },
    },
    sparkcloud = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = false,
      properties = {
        airdrag            = 0,
        alwaysvisible      = true,
        colormap           = [[0.1 0.2 0.6 0.7	0.1 0.1 0.3 1.0		0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.3 r0.3, 0]],
        numparticles       = 2,
        particlelife       = 18,
        particlelifespread = 10,
        particlesize       = [[7 r4]],
        particlesizespread = 2,
        particlespeed      = 20,
        particlespeedspread = 6,
        pos                = [[r-0.5 r0.5, 1 r2, r-0.5 r0.5]],
        sizegrowth         = 1.0,
        sizemod            = 3.0,
        texture            = [[citadellcloud2]],
        useairlos          = true,
      },
    },
	poof01 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[0.1 0.2 0.6 1.0	0.1 0.1 0.3 1.0		0 0 0 0.0]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 12,
        emitvector         = [[0, 0, 1]],
        gravity            = [[0, 0, 0]],
        numparticles       = 12,
        particlelife       = 42,
        particlelifespread = 5,
        particlesize       = 5,
        particlesizespread = 2,
        particlespeed      = 3,
        particlespeedspread = 5,
        pos                = [[r-1 r1, 1, r-1 r1]],
        sizegrowth         = 1.0001,
        sizemod            = 1.0,
        texture            = [[citadellcloud2]],
        useairlos          = true,
      },
    },
	
	
	
	
  },

}

