-- blood_spray

return {
  ["greenbloodspray"] = {
   	 spark = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.2 1 0.2 0.01   0.1 0.8 0.1  0.01 	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 40,
        emitvector         = [[0,1,0]],
        gravity            = [[0, -0.17, 0]],
        numparticles       = 2,
        particlelife       = 27,
        particlelifespread = 17,
        particlesize       = 0.5,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1.001,
        sizemod            = 1.0,
        texture            = [[bubble]],
        useairlos          = false,
      },
    },
	
		blooddrops2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 1,
        colormap           = [[0.2 1 0.2 0.01   0.1 0.8 0.1  0.01 	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[-0.05r0.051, -0.07, -0.05r0.05]],
        numparticles       = 3,
        particlelife       = 19,
        particlelifespread = 22,
        particlesize       = 1,
        particlesizespread = 13,
        particlespeed      = 1,
        particlespeedspread = 0.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[0.0 r.35]],
        sizemod            = 1.0,
        texture            = [[fireSparks]],
        useairlos          = false,
      },
    },
	
	    bitmapmuzzleflame = {
          air                = true,
          class              = [[CBitmapMuzzleFlame]],
          count              = 2,
          ground             = true,
          underwater         = 1,
          water              = true,
          properties = {
           colormap           = [[0.2 1 0.2  .39   0.1 0.9 0.1  .39		0 0 0 0.0001  ]],
             dir                = [[-1 r2, -1 r2, -1 r2]],
            frontoffset        = 0,
            fronttexture       = [[fire]],--redexplo
            length             = 7,
            sidetexture        = [[fire]],
            size               = 7,
            sizegrowth         = 1,
            ttl                = 20,
          },
        },
	
  },

}
