-- massbeamimpact

return {
  ["massbeamimpact"] = {
    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.2,
      circlegrowth       = 4,
      flashalpha         = 0.5,
      flashsize          = 110,
      ground             = true,
      ttl                = 10,
      water              = true,
      color = {
        [1]  = 0.5,
        [2]  = 0,
        [3]  = 1,
      },
    },
    poof = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.9 0.9 0.9 0.04	0.5 0.0 1.0 0.01	0.5 0.1 1.0 0.01	0 0 0 0.00]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 8,
        particlelife       = 10,
        particlelifespread = 0,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 10,
        particlespeedspread = 5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[flashside1]],
        useairlos          = false,
      },
    },
    purpleglow = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 1.0,
        maxheat            = 10,
        pos                = [[r-2 r2, r-2 r2, r-2 r2]],
        size               = [[5 r5]],
        sizegrowth         = [[5 r10]],
        speed              = [[0, 1 0, 0]],
        texture            = [[laserendpurple]],
      },
    },
    strips = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
        colormap           = [[0.9 0.9 0.9 0.04	0.5 0.0 1.0 0.01	0.5 0.1 1.0 0.01	0 0 0 0.00]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 30,
        particlelife       = 10,
        particlelifespread = 0,
        particlesize       = 20,
        particlesizespread = 20,
        particlespeed      = 10,
        particlespeedspread = 15,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[longshot]],
        useairlos          = false,
      },
    },
  },

}

