-- missiletrail2

return {
  ["missiletrail2"] = {
    dirtw1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = false,
        colormap           = [[0.9 0.9 0.9 1.0	0.5 0.5 0.9 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = 10,
        particlelife       = 15,
        particlelifespread = 10,
        particlesize       = 3,
        particlesizespread = 5,
        particlespeed      = 1,
        particlespeedspread = 5,
        pos                = [[r-1 r1, 1, r-1 r1]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[randdots]],
        useairlos          = false,
      },
    },
    fadedsmoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0 0 0 0   0 0 0 0   0.2 0.2 0.2 0.25   0.1 0.1 0.1 0.15	   0.0 0.0 0.0 0.0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[0.05,0.02,0]],
        numparticles       = [[0 r2.6 k2]],
        particlelife       = 10,
        particlelifespread = 60,
        particlesize       = 20,
        particlesizespread = 9,
        particlespeed      = 1,
        particlespeedspread = 10,
        pos                = [[0,0,0]],
        sizegrowth         = [[0.7 r.5]],
        sizemod            = 1,
        texture            = [[dirt]],
        useairlos          = false,
      },
    },
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        alwaysvisible      = false,
        colormap           = [[1 1 1 .01    1 1 1 .01		0 0 0 0.0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 1.5,
        particlelifespread = 1,
        particlesize       = 5,
        particlesizespread = 7,
        particlespeed      = 20,
        particlespeedspread = 5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[flare]],
        useairlos          = true,
      },
    },
    groundflash = {
      alwaysvisible      = false,
      circlealpha        = 0.0,
      circlegrowth       = 6,
      flashalpha         = 0.5,
      flashsize          = 40,
      ttl                = 3,
      color = {
        [1]  = 1,
        [2]  = 0.69999998807907,
        [3]  = 0,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = .95,
        colormap           = [[0 0 0 0   0.4 0.4 0.4 0.5   0.4 0.4 0.4 0.3	   0.0 0.0 0.0 0.0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 15,
        emitvector         = [[dir]],
        gravity            = [[0.05,0.02,0]],
        numparticles       = [[1 r3]],
        particlelife       = 21,
        particlelifespread = 40,
        particlesize       = 5,
        particlesizespread = 8,
        particlespeed      = 2,
        particlespeedspread = 4,
        pos                = [[-10 r20, -10 r20, -10 r20]],
        sizegrowth         = .1,
        sizemod            = .99,
        texture            = [[dirt]],
        useairlos          = false,
      },
    },
  },

}

