-- missiletrail1

return {
  ["missiletrail1"] = {
    dirtw1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0.9 0.9 0.9 1.0	0.5 0.5 0.9 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = 10,
        particlelife       = 15,
        particlelifespread = 10,
        particlesize       = 3,
        particlesizespread = 5,
        particlespeed      = 1,
        particlespeedspread = 5,
        pos                = [[r-1 r1, 1, r-1 r1]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[randdots]],
      },
    },
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 22,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        alwaysvisible      = true,
        colormap           = [[0.9 0.9 0.7 0.01	0.5 0.4 0.3 0.02	0.9 0.8 0.1 0.02		0 0 0 0.0]],
        directional        = true,
        emitrot            = 2,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 1.5,
        particlelifespread = 1,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = [[-6 i3]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.5,
        sizemod            = 1.0,
        texture            = [[firesprite]],
      },
    },
    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.0,
      circlegrowth       = 6,
      flashalpha         = 0.9,
      flashsize          = 25,
      ground             = true,
      ttl                = 3,
      water              = true,
      color = {
        [1]  = 1,
        [2]  = 0.5,
        [3]  = 0,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 6,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.4 0.4 0.4 0.5   0.4 0.4 0.4 0.3	0.0 0.0 0.0 0.0]],
        directional        = true,
        emitrot            = 2,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[r-0.1 r0.1, r-0.1 r1, r-0.1 r0.1]],
        numparticles       = 1,
        particlelife       = 15,
        particlelifespread = 15,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = [[-10 i7]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
  },

}

