-- redlight

return {
  ["portalenter"] = {
  	  alwaysvisible      = true,

	 lensflare = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
         colormap           = [[0.95 0.95 0.95  0.01	0.95 0.95 0.95  0.01 	0.95 0.95 0.95  0.01 	   	0 0 0 0.0]],
        directional        = true,
        emitrot            = 10,
        emitrotspread      = 10,
        emitvector         = [[0, 0 r0.001 , 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 55,
        particlelifespread = 0,
        particlesize       = [[3 ]],
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 50, 0]],
        sizegrowth         = 1.000000000000001,
        sizemod            =  0.91,
        texture            = [[lensflareCenter]],
        useairlos          = false,
      },
    },
	
		 expandstrobe = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
         colormap           = [[0.95 0.95 0.95  0.01	0.95 0.95 0.95  0.01 	0.95 0.95 0.95  0.01 	   	0 0 0 0.0]],
        directional        = false,
        emitrot            = 10,
        emitrotspread      = 10,
        emitvector         = [[0, 0 r0.001 , 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 90,
        particlelifespread = 0,
        particlesize       = [[30 ]],
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 50, 0]],
        sizegrowth         = 1.000000000000001,
        sizemod            =  0.975,
        texture            = [[expandingstrobe]],
        useairlos          = false,
      },
    },	 
	
	innerspiral = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
         colormap           = [[0.95 0.95 0.95  0.01	0.95 0.95 0.95  0.01 	0.95 0.95 0.95  0.01 	   	0 0 0 0.0]],
        directional        = false,
        emitrot            = 10,
        emitrotspread      = 10,
        emitvector         = [[0, 0 r0.001 , 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 90,
        particlelifespread = 0,
        particlesize       = [[6 ]],
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 50, 0]],
        sizegrowth         = 1.000000000000001,
        sizemod            =  0.975,
        texture            = [[innerswirl]],
        useairlos          = false,
      },
    },
	
	outerspiral = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
         colormap           = [[0.95 0.95 0.95  0.01	0.95 0.95 0.95  0.01 	0.95 0.95 0.95  0.01 	   	0 0 0 0.0]],
        directional        = false,
        emitrot            = 10,
        emitrotspread      = 10,
        emitvector         = [[0, 0 r0.001 , 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 90,
        particlelifespread = 0,
        particlesize       = [[24 ]],
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 50, 0]],
        sizegrowth         = 1.000000000000001,
        sizemod            =  0.975,
        texture            = [[outerspira]],
        useairlos          = false,
      },
    },
	
	
	   spark = {
      air                = true,
      class              = [[CSimpleParticleSystem]],	
	
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.2 0.8 1 0.01  0.2 0.8 1 0.01  	0 0 0 0.01]],	
	
        directional        = true,
        emitrot            = 5,
        emitrotspread      = 42,
        emitvector         = [[0 r-0.3 r0.3,-0.3, r-0.3 r0.3]],
      gravity            = [[0, 0.007, 0]], 
       numparticles       = 1,
        particlelife       = 35,
        particlelifespread = 20,
        particlesize       = 1.5,
        particlesizespread = 0,
        particlespeed      = 0.5,
        particlespeedspread = 1,
        pos                = [[0, 50, 0]],
	
        sizegrowth         = [[0.0 r.20]],
        sizemod            = 1.0,
        texture            = [[slicerspark1]],
		
        useairlos          = false,
      },
    },   

	spark2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],	
	
      count              = 15,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.2 0.8 1 0.01  0.2 0.8 1 0.01  	0 0 0 0.01]],	
	
        directional        = true,
        emitrot            = 5,
        emitrotspread      = 42,
        emitvector         = [[0 r-0.3 r0.3,0.3, r-0.3 r0.3]],
      gravity            = [[0, -0.007, 0]], 
       numparticles       = 1,
        particlelife       = 35,
        particlelifespread = 20,
        particlesize       = 1.5,
        particlesizespread = 0,
        particlespeed      = 0.5,
        particlespeedspread = 1,
        pos                = [[0, 50, 0]],
	
        sizegrowth         = [[0.0 r.20]],
        sizemod            = 1.0,
        texture            = [[slicerspark2]],
		
        useairlos          = false,
      },
    },  
  
		 whiteglow = {
			  air                = true,
			  class              = [[heatcloud]],
			  count              = 1,
			  ground             = true,
			  water              = true,
			  properties = {
				alwaysvisible      = true,
				heat               = 1,
				heatfalloff        = 0.1,
				maxheat            = 1,
				pos                = [[0,0,0]],
				size               = 35,
				sizegrowth         = 8,
				speed              = [[0,0,0]],
				texture            = [[laserendblue]],
			  },
			},
  

	
	},
  }


