-- dirt

return {
  ["vortport"] = {
       poof02 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
		  properties = {
			airdrag            = 0.1,
			alwaysvisible      = true,
			--180 230 29 0.7 0.9 0.1
			colormap           = [[ 0.7 0.9 0.1 0.01	 0.7 0.9 0.1 0.01	0.0 0.0 0.0 0.01]],
			directional        = false,
			emitrot            = 45,
			emitrotspread      = 32,
			emitvector         = [[0, 1, 0]],
			gravity            = [[0, -0.005, 0]],
			numparticles       = 1,
			particlelife       = 3,
			particlelifespread = 8,
			particlesize       = 2,
			particlesizespread = 0,
			particlespeed      = 1,
			particlespeedspread = 3,
			pos                = [[0, 2, 0]],
			sizegrowth         = 0.8,
			sizemod            = 1.0,
			texture            = [[randdots]],
			useairlos          = false,
					},
				},
				
				
				 electricarcs1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.7 0.9 0.1 0.04	0.6 0.9 0.05 0.01	0.5 0.9 0.02 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 28,
        particlelife       = 20,
        particlelifespread = 5,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[lightening]],
        useairlos          = false,
      },
    },
    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.6,
      circlegrowth       = 6,
      flashalpha         = 0.9,
      flashsize          = 220,
      ground             = true,
      ttl                = 13,
      water              = true,
      color = {
        [1]  = 0.7,
        [2]  = 0.9,
        [3]  = 0.1,
      },
    },
    moredots = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[1.0 1.0 1.0 0.05	0.2 0.5 0.9 0.01	0.1 0.1 0.8 0.00]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 16,
        particlelife       = 5,
        particlelifespread = 16,
        particlesize       = 25,
        particlesizespread = 0,
        particlespeed      = 10,
        particlespeedspread = 3,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1,
        texture            = [[randdots]],
        useairlos          = false,
      },
    },
    whiteglow = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 1.1,
        maxheat            = 15,
        pos                = [[0, 5, 0]],
        size               = 10,
        sizegrowth         = 20,
        speed              = [[0, 1 0, 0]],
        texture            = [[laserendgreen]],
      },
    },
  
  
  
  },
  

}

