-- yellowbeammuzzle

return {
  ["yellowbeammuzzle"] = {
    bitmapmuzzleflame = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.7 0.4 0.01    1 0.5 0.2 0.01	0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0.05,
        fronttexture       = [[flash3]],
        length             = 30,
        sidetexture        = [[shot]],
        size               = 12,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    lines = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0 0 0 0   1 1 0.2 0.1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 30,
        particlelifespread = 10,
        particlesize       = 6,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = 0.1,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[randdots]],
      },
    },
    whiteglow = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 3.5,
        maxheat            = 15,
        pos                = [[0, 0, 0]],
        size               = 9,
        sizegrowth         = 40,
        speed              = [[0, 0, 0]],
        texture            = [[glow]],
      },
    },
    yellowglow = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 3.5,
        maxheat            = 15,
        pos                = [[0, 0, 0]],
        size               = 1,
        sizegrowth         = 40,
        speed              = [[0, 0, 0]],
        texture            = [[laserendyellow]],
      },
    },
  },

}

