local unitName = "jmovingfac1"
local unitDef = {
name = "Firstborn Unituterus",
Description = "Transports the TraFactory, provides visuals",
objectName = "jFirstBorn.s3o",
script = "jmobileFactory1.lua",
buildPic = "placeholderj.png",
--costbuildCostMetal = 850,
buildCostEnergy = 340,
buildTime = 50,
--HealthmaxDamage = 2300,
maxDamage = 1200,
idleAutoHeal = 3,
--MovementAcceleration = 0.4,
BrakeRate = 0.3,
FootprintX = 1,
FootprintZ = 1,
MaxSlope = 5,
MaxVelocity = 0.5,
MaxWaterDepth = 20,
MovementClass = "Default2x2",
TurnRate = 150,
isMetalExtractor = false,
sightDistance = 500,
nanocolor=[[0.2 0.9 0.5]],
onoffable=true,
activateWhenBuilt =false,
Builder = false,
CanAttack = false,
CanGuard = false,
CanMove = true,
CanPatrol = false,
CanStop = true,
LeaveTracks = true,
 Category = [[LAND]],
EnergyStorage = 0,
	EnergyUse = 15,
	MetalStorage = 0,
	EnergyMake = 0,
 	MakesMetal = 0,
 	MetalMake = 0,
	   customParams = {},
 sfxtypes = {				
	  explosiongenerators = {				 
					"custom:dirt",
             		"custom:bloodspray",
				    "custom:greenlight",
				    "custom:fruitwater",				
				    "custom:jbuildingexaust"				
					},
},
}return lowerkeys({ [unitName] = unitDef })