return {
--centrail 
  ["cadvisor"]= {active="Reeducate Citizen", passive="Reeducation \nin Progress"},
  ["builux"]= {active="Alarm On\n Retract\ninto\nGround", passive="Alarm \n Emerge\nfrom\nGround"},
  ["mbuilux"]= {active="Alarm On\n Retract\ninto\nGround", passive="Alarm \n Emerge\nfrom\nGround"},
  ["condepot"]= {active="Alarm On\n Retract\ninto\nGround", passive="Alarm \n Emerge\nfrom\nGround"},
  ["ccrabsynth"]= {active="Deploy", passive="Mobilize  "},
  ["cgamagardener"]= {active="Activate\nRadiation", passive="Deactivate\nRadiation"},
  ["cnanorecon"]= {active="Call\n Citadell", passive="Portalstorm\n pending"},
  ["cgatefort"]= {active="GateRail\nOn", passive="GateRail\nOff"},
  ["cwallbuilder"]= {active="Terraform \nOn", passive="Terraform \nOff"},
  ["mtw"]= {active="Build\nTrooper ", passive="Build\nSynthsoldier"},
  ["css"]= {active="Torch\nEnvironment", passive="Cease\nFire"},
  ["bg"]= {active="Ballistic\nShield", passive="ATAC\nMODE"},
  ["bg2"]= {active="Ballistic\nShield", passive="ATAC\nMODE"},
  ["cwaterextractor"]= {active="Harvest\nWater", passive="Stop\nHarvest"},
  ["mdigg"]= {active="Start\nMining", passive="Stop\nMining"},
  ["mdiggmex"]= {active="Stop\nMining", passive="Start\nMining"},
  ["citadell"]= {active="Raise\nShield", passive="Lower\nShield"},
  ["cpaxcentrail"]= {active="", passive="Enforce\nCompliance\n via\nHostageblock"},
  ["comendbonker"]= {active="Conset&\nConfirm", passive="Repeat\nConfirmation"},
  ["sentrynell"]= {active="Activate\n Motionsensor", passive="Deactivate\n Motionsensor"},
  ["chivemind"]= {active="Hyper\n A.I.ctivity", passive="AI-Node\n Ready"},

--journeyman
  ["jabyss"]= {active="End this\nWorld", passive="World Ends"},
  ["jbonsai"]= {active="Extract\n Corewater", passive="Stop\n Corewater"},
  ["jfiredancer"]= {active="Sacrifice", passive="Sacrifice"},
  ["jbeherith"]= {active="Amok", passive="Amok Active"},
  ["beanstalk"]= {active="Unroot", passive="Reroot"},
  ["skinfantry"]= {active="Ambush\nMode\nOn", passive="Ambush\nMode\nOff"},
  ["tiglil"]= {active="Ambush\nMode\nOn", passive="Ambush\nMode\nOff"},
  ["jtree1"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree2"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree2active"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree3"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree41"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree42"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree43"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree44"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree45"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree46"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree47"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree48"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtree49"]= {active="Deny \n Energy", passive="Sucked\ndry"},
  ["jtyrion"]= {active="Turn\n coat", passive="Traitor"},
  ["jhivemind"]= {active="Hivemind\n Uebertactics", passive="Minds Linked\n Sleeping"}
}
